### PR TITLE
UH9 Meet The Team

### PR DESCRIPTION
**Pull request by nikita-jha**
I completed half of the "Meat the Team Section" - Tech, Sponsorship, and half of logistics from this list (https://docs.google.com/document/d/1yNJsOhzlDoDhujh781YkRICTjUZpIOvPQm7Q1gBgB74/edit)

### CODE REVIEW

**Comment by alexteal** [comment]
Ok. Too much in one PR. I'm sorry.

**Comment by alexteal** [comment]
# TODO
- director image
- byte image
- max's card is displaying Dylan Myers'
- include new "Advisor's" section
- - saba
- - Genki
- - Matt Santoro
- - Aniyah

**Comment by alexteal** [comment]
Removed duplicates, for future use, check out 
```bash
❯ fdupes -h
Usage: fdupes [options] DIRECTORY...

 -r --recurse            for every directory given follow subdirectories
                         encountered within
...
```

really useful command, checks for same files recursively.

**Comment by shawnpradeep** [comment]
image
Bitmoji for Austin Kral of UH7 came through as well

**Comment by alexteal** [comment]
# DONE
Good to merge @shawnpradeep

**Comment by alexteal** [comment]
Ok, now we're 
# DONE

**Review by shawnpradeep — APPROVED** [review]
looks good guys, appreciate yall

**Pull request merged**
